language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt 
  - pip install coveralls
  - pip install coverage 
  - pip install nose
# command to run tests 
script: 
  - nosetests --with-coverage --cover-package=app

after_success: 
  - coveralls