language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt 
  - pip install coveralls
  - pip install coverage 
  - pip install nose

# command to run tests 
script: 
  - nosetests --with-coverage --cover-package=app
  # - coverage run -m nose
  # - coverage report -m

after_success: 
  - coveralls